Improve safety of autodescribe
Quote file names so embedded spaces will work. Output shell-safe
arguments in verbose mode. Use mktemp to generate a unique temporary
file. Switch to the more readable $() subshell syntax.  Use -z to test
for an empty variable.  Remove the old changelog and add the public
domain disclaimer.

diff --git a/autodescribe b/autodescribe
--- a/autodescribe
+++ b/autodescribe
@@ -1,19 +1,18 @@
 #!/bin/sh
 # autodescribe - automatically extract comments from files
-# $Id: autodescribe,v 1.2 1998/06/08 16:15:42 dan Exp $
-#
-# $Log: autodescribe,v $
-# Revision 1.2  1998/06/08 16:15:42  dan
-# Added RPM file type.
-#
-# 97-03-15 Dan Fandrich
-# 95-12-05 Dan Fandrich
+# Placed into the public domain by Dan Fandrich <dan@coneharvesters.com>
+# See the file COPYING for details of how CC0 applies to this file.
 
 # Program to run for each description
 DESCRIBE="describe --"
 
 # Non-null for old version of unzip (some time before 5.12)
 #OLDUNZIP=1
+
+# Print a shell-quoted version of the first argument
+shquote() {
+	echo "$1" | awk -v q="'" '{gsub(q, q "\\" q q, $0); printf "%s", q $0 q;}'
+}
 
 # Get comment from a compressed tar file
 # Comment is taken from a man page file with name *.[0-9]
@@ -22,184 +21,185 @@ DESCRIBE="describe --"
 # symbolic links matching *.[0-9] at least with GNU tar 1.11.2
 # BUG: tar will extract all files if path ends in a number, e.g. playmidi-2.3/foo
 comment_tgz () {
-	COMMENT=`tar -xOkzf $f \*.man \*.\[0-9\] 2>/dev/null | grep -A 1 '^.SH NAME' | tail -1 | \
-		sed 's/^.* \\\\- //'`
-	if [ "$COMMENT" = "" ] ; then
-		COMMENT=`tar -xOkzf $f \*.lsm 2>/dev/null | sed -n 's/^Title: *//p'`
+	COMMENT=$(tar -xOkzf "$f" \*.man \*.\[0-9\] 2> /dev/null | grep -A 1 '^.SH NAME' | tail -1 | \
+		sed 's/^.* \\\\- //')
+	if [ -z "$COMMENT" ] ; then
+		COMMENT=$(tar -xOkzf "$f" \*.lsm 2> /dev/null | sed -n 's/^Title: *//p')
 	fi
 }
 
 # Get comment from a .lzh file
 # Comment must be stored as one line in a file called 'desc.sdi'
 comment_lzh () {
-	COMMENT=`lha pq $f desc.sdi | tr '\n' ' '`
+	COMMENT=$(lha pq "$f" desc.sdi | tr '\n' ' ')
 }
 
 # Get comment from a .zip file
 comment_zip () {
-if [ "$OLDUNZIP" = "" ] ; then
-	if [ `unzip -z $f dummy-file-to-eliminate-output | \
-	   wc -l` -gt 1 ] ; then
-		COMMENT=`unzip -z $f dummy-file-to-eliminate-output | \
-		head -2 | tail -1`
+if [ -z "$OLDUNZIP" ] ; then
+	if [ $(unzip -z "$f" dummy-file-to-eliminate-output | \
+	   wc -l) -gt 1 ] ; then
+		COMMENT=$(unzip -z "$f" dummy-file-to-eliminate-output | \
+		head -2 | tail -1)
 
-	elif unzip -vqq $f desc.sdi > /dev/null ; then
-		COMMENT=`unzip -caq $f desc.sdi`
+	elif unzip -vqq "$f" desc.sdi > /dev/null ; then
+		COMMENT=$(unzip -caq "$f" desc.sdi)
 	fi
 
 else
 # old unzip
 
-	if unzip -v $f dummy-file-to-eliminate-output | \
+	if unzip -v "$f" dummy-file-to-eliminate-output | \
 	   grep '^\[.*\] comment:' > /dev/null ; then
 # file has comment
-		COMMENT=`unzip -v $f dummy-file-to-eliminate-output | \
-		head -2 | tail -1`
-	elif unzip -vqq $f desc.sdi > /dev/null ; then
-		COMMENT=`unzip -caq $f desc.sdi`
+		COMMENT=$(unzip -v "$f" dummy-file-to-eliminate-output | \
+		head -2 | tail -1)
+	elif unzip -vqq "$f" desc.sdi > /dev/null ; then
+		COMMENT=$(unzip -caq "$f" desc.sdi)
 	fi
 fi
 }
 
 # Get comment from a .zoo file
 comment_zoo () {
-	COMMENT=`zoo vc $f dummy-file-to-eliminate-output | \
-		sed -n -e 's/^>> //p' | tr '\n' ' '`
-	if [ "$COMMENT" = "" ] && zoo vq $f desc.sdi > /dev/null ; then
-		COMMENT=`zoo xpq $f desc.sdi`
+	COMMENT=$(zoo vc "$f" dummy-file-to-eliminate-output | \
+		sed -n -e 's/^>> //p' | tr '\n' ' ')
+	if [ -z "$COMMENT" ] && zoo vq "$f" desc.sdi > /dev/null ; then
+		COMMENT=$(zoo xpq "$f" desc.sdi)
 	fi
 }
 
 # Get comment from an RPM package
 comment_rpm () {
-	COMMENT=`rpm -qp --queryformat '%{SUMMARY}' $f`
+	COMMENT=$(rpm -qp --queryformat '%{SUMMARY}' "$f")
 }
 
 # Get comment from a PostScript file
 comment_ps () {
-	COMMENT=`sed -n 's/^%%Title: *//p' $f | head -1`
-	if [ "$COMMENT" = "" ] ; then
+	COMMENT=$(sed -n 's/^%%Title: *//p' "$f" | head -1)
+	if [ -z "$COMMENT" ] ; then
 # Try for an alternate comment
 # Look for a comment beginning with one or more % followed by a space
-		COMMENT=`sed -n 's/^%%*  *//p' $f | head -1`
+		COMMENT=$(sed -n 's/^%%*  *//p' "$f" | head -1)
 	fi
 }
 
 # Get comment from a PostScript font file
 comment_psfont () {
-	COMMENT=`sed -n 's/^\/FullName[ 	]*(\(.*\)).*$/\1/p'  $f | head -1`
-	if [ "$COMMENT" = "" ] ; then
-# Try for an alternate comment
-		COMMENT=`sed -n 's/^\/FontName[ 	]*\/\([^ 	]*\).*$/\1/p' $f | head -1`
+	COMMENT=$(sed -n 's/^\/FullName[ 	]*(\(.*\)).*$/\1/p' "$f" | head -1)
+	if [ -z "$COMMENT" ] ; then
+        # Try for an alternate comment
+		COMMENT=$(sed -n 's/^\/FontName[ 	]*\/\([^ 	]*\).*$/\1/p' "$f" | head -1)
 	fi
 }
 
 # Get comment from a news or mail file
 comment_subject () {
-	COMMENT=`sed -n 's/^Subject: *//p' $f | head -1`
+	COMMENT=$(sed -n 's/^Subject: *//p' "$f" | head -1)
 	if [ "$COMMENT" = "" ] ; then
 # Try for an alternate comment
-		COMMENT=`sed -n 's/^Content-Description: *//p' $f | head -1`
+		COMMENT=$(sed -n 's/^Content-Description: *//p' "$f" | head -1)
 	fi
 }
 
 # Get comment from a TIFF image
 comment_tiff () {
-	COMMENT=`tiffdump $f | grep -A1 '\[ImageDescription ' | tail -1`
-	if [ "$COMMENT" = "" ] ; then
+	COMMENT=$(tiffdump "$f" | grep -A1 '\[ImageDescription ' | tail -1)
+	if [ -z "$COMMENT" ] ; then
 # Try for an alternate comment
-		COMMENT=`tiffdump $f | grep -A1 '\[DocumentName ' | tail -1`
-	elif [ "$COMMENT" = "" ] ; then
+		COMMENT=$(tiffdump "$f" | grep -A1 '\[DocumentName ' | tail -1)
+	elif [ -z "$COMMENT" ] ; then
 # Try for an alternate comment
-		COMMENT=`tiffdump $f | grep -A1 '\[Artist ' | tail -1`
+		COMMENT=$(tiffdump "$f" | grep -A1 '\[Artist ' | tail -1)
 	fi
 }
 
 # Get comment from C source file
 comment_c () {
-	COMMENT=`sed -n '/\/\*/,/\*\//{
+	COMMENT=$(sed -n '/\/\*/,/\*\//{
 			/\/\*/s/^.*\/\*[ 	]*//
 			s/^[ 	]*//
 			s/[ 	]*$//
 			p 
-			}' $f | head -3 | tr '\n' ' '`
+			}' "$f" | head -3 | tr '\n' ' ')
 }
 
 # Get comment from Pascal source file
 comment_pascal () {
-	COMMENT=`sed -n '/(\*/,/\*)/{
+	COMMENT=$(sed -n '/(\*/,/\*)/{
 			/(\*/s/^.*(\*//
 			s/^[ 	]*//
 			s/[ 	]*$//
 			p 
-			}' $f | head -3 | tr '\n' ' '`
+			}' "$f" | head -3 | tr '\n' ' ')
 }
 
 # Get comment from an assembly language file
 comment_asm () {
-	COMMENT=`sed -n 's/^[ 	]*title[ 	]*//p' $f`
+	COMMENT=$(sed -n 's/^[ 	]*title[ 	]*//p' "$f")
 }
 
 # Get comment from a GIF image
 comment_gif () {
-	COMMENT=`giftext $f | sed -n 's/^	Image Size - Left = [0-9]*, Top = [0-9]*, *//p' | head -1`
+	COMMENT=$(giftext "$f" | sed -n 's/^	Image Size - Left = [0-9]*, Top = [0-9]*, *//p' | head -1)
 }
 
 # Get comment from a JPEG JFIF image
 comment_jpeg () {
-	COMMENT=`djpeg -verbose -fast -scale 1/8 -grayscale $f 2>&1 | grep -A1 '^Comment, length' | head -2 | tail -1`
+	COMMENT=$(djpeg -verbose -fast -scale 1/8 -grayscale "$f" 2>&1 | grep -A1 '^Comment, length' | head -2 | tail -1)
 }
 
 # Get comment from the first nonblank line of a text file
 comment_first_line () {
+	TMPFILE="$(mktemp)"
 	(
 		while read line ; do
-			COMMENT=`echo $line | sed -n '1s/^ *//p'`
+			COMMENT=$(echo "$line" | sed -n '1s/^ *//p')
 			if [ "$COMMENT" != "" ] ; then
 				break
 			fi
 		done
-		echo $COMMENT
-	) < $f >/tmp/autodesc.$$
+		echo "$COMMENT"
+	) < "$f" > "$TMPFILE"
 # Unfortunately, read can't read from a pipe
-	read COMMENT </tmp/autodesc.$$
-	rm -f /tmp/autodesc.$$
+	read COMMENT < "$TMPFILE"
+	rm -f "$TMPFILE"
 }
 
 # Get comment from a shell script file
 comment_sh () {
 	# delete #!/bin/sh line and blank comment lines
 	# comment must be in the first 10 lines of the file
-	COMMENT=`sed -n -e '10,$d' -e '/^#\!/d' -e '/^#* *$/d' -e 's/^# *//p' $f | head -1`
+	COMMENT=$(sed -n -e '10,$d' -e '/^#\!/d' -e '/^#* *$/d' -e 's/^# *//p' "$f" | head -1)
 }
 
 # Get comment from a Python source file
 comment_py () {
 	# delete #!/bin/sh line and blank comment lines
 	# comment must be in the first 10 lines of the file
-	COMMENT=`sed -n -e '10,$d' -e '/^#\!/d' -e '/^#* *$/d' -e 's/^# *//p' -e "s/^''' *//p" $f | head -1`
+	COMMENT=$(sed -n -e '10,$d' -e '/^#\!/d' -e '/^#* *$/d' -e 's/^# *//p' -e "s/^''' *//p" "$f" | head -1)
 }
 
 # Get comment from the first line of a text file
 comment_html () {
-	COMMENT=`sed -n '/<TITLE>/s/<[^>]*>//gp' $f`
+	COMMENT=$(sed -n '/<TITLE>/s/<[^>]*>//gp' "$f")
 }
 
 # Get comment from an XBM image
 # Could extract image size here as well
 comment_xbm () {
-	COMMENT=`sed -n 's/^.* \(.*\)_bits.*$/\1/p' $f`
+	COMMENT=$(sed -n 's/^.* \(.*\)_bits.*$/\1/p' "$f")
 }
 
 # Get comment from an XPM image
 # Could extract image size here as well
 comment_xpm () {
-	COMMENT=`sed -n 's/^.* \(.*\)_xpm.*$/\1/p' $f`
+	COMMENT=$(sed -n 's/^.* \(.*\)_xpm.*$/\1/p' "$f")
 }
 
 # Get comment from a pnm image
 comment_pbm () {
-	COMMENT=`pnmfile $f | sed -n 's/^.*:	//p'`
+	COMMENT=$(pnmfile "$f" | sed -n 's/^.*:	//p')
 }
 
 
@@ -234,15 +234,15 @@ if [ $# -eq 0 ] ; then
 	exit 1
 fi
 
-if [ $1 = -q ] ; then
+if [ "$1" = "-q" ] ; then
 	VERBOSE=0
 	shift
 else
 	VERBOSE=1
 fi
 
-if [ $1 = -t ] ; then
-	SETTYPE=$2
+if [ "$1" = "-t" ] ; then
+	SETTYPE="$2"
 	shift
 	shift
 else
@@ -250,16 +250,16 @@ else
 fi
 
 # Loop through files, commenting one at a time
-for f in $* ; do
+for f in "$@" ; do
 	COMMENT=""
 
-	if ! [ -r $f ] ; then
-		echo $f: Not found 1>&2
+	if ! [ -r "$f" ] ; then
+		echo "$f": Not found 1>&2
 		continue
 	fi
 
-	if [ "$SETTYPE" != "" ] ; then
-		TYPE=$SETTYPE
+	if [ -n "$SETTYPE" ] ; then
+		TYPE="$SETTYPE"
 	else
 		case "$f" in
 			*.c | *.h)
@@ -296,7 +296,7 @@ for f in $* ; do
 				;;
 			*.sh)	TYPE=sh
 				;;
-		*.ps)	TYPE=ps
+			*.ps)	TYPE=ps
 				;;
 			*.py)	TYPE=py
 				;;
@@ -327,18 +327,21 @@ for f in $* ; do
 		esac
 	fi
 
-	if [ "$TYPE" = "" ] ; then
-		echo $f: Not a known file type 1>&2
+	if [ -z "$TYPE" ] ; then
+		echo "$f": Not a known file type 1>&2
 	else
-# Find the comment
-		comment_$TYPE
+		# Call the right function to find the comment
+		comment_"$TYPE"
 	fi
 
-	if [ "$COMMENT" = "" ] ; then
-		echo $f: No comment found 1>&2
+	if [ -z "$COMMENT" ] ; then
+		echo "$f": No comment found 1>&2
 	else
-		if [ $VERBOSE -eq 1 ] ; then
-			echo "$f" \""$COMMENT"\"
+		if [ "$VERBOSE" -eq 1 ] ; then
+			shquote "$f"
+			printf " "
+			shquote "$COMMENT"
+			echo ""
 		fi
 		$DESCRIBE "$f" "$COMMENT"
 	fi
