Changed return code for argument error.

diff --git a/fv b/fv
--- a/fv
+++ b/fv
@@ -1,8 +1,12 @@
 #!/bin/sh
 # fv - archive and package directory lister
 # Place into the public domain by Dan Fandrich <dan@coneharvesters.com>
-# $Id: fv,v 1.2 2003/04/02 06:37:53 dan Exp $
+# $Id: fv,v 1.3 2003/04/02 07:23:15 dan Exp $
+#
 # $Log: fv,v $
+# Revision 1.3  2003/04/02 07:23:15  dan
+# Changed return code for argument error.
+#
 # Revision 1.2  2003/04/02 06:37:53  dan
 # Bumped version number to 1.1.
 # Exit with the archive list command exit code (in most cases).
@@ -24,7 +28,7 @@ if [ $# -eq 0 ] ; then
 	echo 'fv ver. 1.1'
 	echo 'Usage: fv archive1 [ archive2 ... ]'
 	echo 'Displays directories of many archive types.'
-	exit 1
+	exit 3
 fi
 
 for f in "$@" ; do
